// <auto-generated />
namespace LuvDating.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Friend_keyChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Friend_keyChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202001122335056_Friend_keyChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
