// <auto-generated />
namespace LuvDating.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FriendModel_Added_To_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FriendModel_Added_To_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202001081123235_FriendModel_Added_To_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
